/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PruebaGratisRouteImport } from './routes/prueba-gratis'
import { Route as ConfigurarCuentaRouteImport } from './routes/configurar-cuenta'
import { Route as BienvenidoRouteImport } from './routes/bienvenido'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSeriesRouteRouteImport } from './routes/_authenticated/series/route'
import { Route as AuthenticatedWorkCentersIndexRouteImport } from './routes/_authenticated/work-centers/index'
import { Route as AuthenticatedViewerIndexRouteImport } from './routes/_authenticated/viewer/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTimbresIndexRouteImport } from './routes/_authenticated/timbres/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSeriesIndexRouteImport } from './routes/_authenticated/series/index'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedMassiveDownloadsIndexRouteImport } from './routes/_authenticated/massive-downloads/index'
import { Route as AuthenticatedInvoicingIndexRouteImport } from './routes/_authenticated/invoicing/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCatalogsIndexRouteImport } from './routes/_authenticated/catalogs/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedWorkCentersAddRouteImport } from './routes/_authenticated/work-centers/add'
import { Route as AuthenticatedUsersAddRouteImport } from './routes/_authenticated/users/add'
import { Route as AuthenticatedUsersAdminIdRouteImport } from './routes/_authenticated/users/$adminId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsBusinessRouteImport } from './routes/_authenticated/settings/business'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSeriesCreateRouteImport } from './routes/_authenticated/series/create'
import { Route as AuthenticatedProductsAddRouteImport } from './routes/_authenticated/products/add'
import { Route as AuthenticatedMassiveDownloadsAddRouteImport } from './routes/_authenticated/massive-downloads/add'
import { Route as AuthenticatedInvoicingNewRouteImport } from './routes/_authenticated/invoicing/new'
import { Route as AuthenticatedInvoicingInvoiceIdRouteImport } from './routes/_authenticated/invoicing/$invoiceId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedClientsAddRouteImport } from './routes/_authenticated/clients/add'
import { Route as AuthenticatedReportsSalesIndexRouteImport } from './routes/_authenticated/reports/sales/index'
import { Route as AuthenticatedInvoicingPaymentComplementsIndexRouteImport } from './routes/_authenticated/invoicing/payment-complements/index'
import { Route as AuthenticatedInvoicingCreditNotesIndexRouteImport } from './routes/_authenticated/invoicing/credit-notes/index'
import { Route as AuthenticatedInvoicingBillOfLadingIndexRouteImport } from './routes/_authenticated/invoicing/bill-of-lading/index'
import { Route as AuthenticatedWorkCentersWorkCenterIdEditRouteImport } from './routes/_authenticated/work-centers/$workCenterId/edit'
import { Route as AuthenticatedSeriesEditSeriesIdRouteImport } from './routes/_authenticated/series/edit.$seriesId'
import { Route as AuthenticatedSeriesSeriesIdEditRouteImport } from './routes/_authenticated/series/$seriesId/edit'
import { Route as AuthenticatedProductsProductIdEditRouteImport } from './routes/_authenticated/products/$productId/edit'
import { Route as AuthenticatedMassiveDownloadsViewerDownloadIdRouteImport } from './routes/_authenticated/massive-downloads/viewer.$downloadId'
import { Route as AuthenticatedClientsClientIdEditRouteImport } from './routes/_authenticated/clients/$clientId/edit'

const PruebaGratisRoute = PruebaGratisRouteImport.update({
  id: '/prueba-gratis',
  path: '/prueba-gratis',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurarCuentaRoute = ConfigurarCuentaRouteImport.update({
  id: '/configurar-cuenta',
  path: '/configurar-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidoRoute = BienvenidoRouteImport.update({
  id: '/bienvenido',
  path: '/bienvenido',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeriesRouteRoute =
  AuthenticatedSeriesRouteRouteImport.update({
    id: '/series',
    path: '/series',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkCentersIndexRoute =
  AuthenticatedWorkCentersIndexRouteImport.update({
    id: '/work-centers/',
    path: '/work-centers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedViewerIndexRoute =
  AuthenticatedViewerIndexRouteImport.update({
    id: '/viewer/',
    path: '/viewer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimbresIndexRoute =
  AuthenticatedTimbresIndexRouteImport.update({
    id: '/timbres/',
    path: '/timbres/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSeriesIndexRoute =
  AuthenticatedSeriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSeriesRouteRoute,
  } as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMassiveDownloadsIndexRoute =
  AuthenticatedMassiveDownloadsIndexRouteImport.update({
    id: '/massive-downloads/',
    path: '/massive-downloads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicingIndexRoute =
  AuthenticatedInvoicingIndexRouteImport.update({
    id: '/invoicing/',
    path: '/invoicing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogsIndexRoute =
  AuthenticatedCatalogsIndexRouteImport.update({
    id: '/catalogs/',
    path: '/catalogs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkCentersAddRoute =
  AuthenticatedWorkCentersAddRouteImport.update({
    id: '/work-centers/add',
    path: '/work-centers/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersAddRoute = AuthenticatedUsersAddRouteImport.update({
  id: '/users/add',
  path: '/users/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersAdminIdRoute =
  AuthenticatedUsersAdminIdRouteImport.update({
    id: '/users/$adminId',
    path: '/users/$adminId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBusinessRoute =
  AuthenticatedSettingsBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSeriesCreateRoute =
  AuthenticatedSeriesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedSeriesRouteRoute,
  } as any)
const AuthenticatedProductsAddRoute =
  AuthenticatedProductsAddRouteImport.update({
    id: '/products/add',
    path: '/products/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMassiveDownloadsAddRoute =
  AuthenticatedMassiveDownloadsAddRouteImport.update({
    id: '/massive-downloads/add',
    path: '/massive-downloads/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicingNewRoute =
  AuthenticatedInvoicingNewRouteImport.update({
    id: '/invoicing/new',
    path: '/invoicing/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicingInvoiceIdRoute =
  AuthenticatedInvoicingInvoiceIdRouteImport.update({
    id: '/invoicing/$invoiceId',
    path: '/invoicing/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsAddRoute = AuthenticatedClientsAddRouteImport.update({
  id: '/clients/add',
  path: '/clients/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsSalesIndexRoute =
  AuthenticatedReportsSalesIndexRouteImport.update({
    id: '/reports/sales/',
    path: '/reports/sales/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicingPaymentComplementsIndexRoute =
  AuthenticatedInvoicingPaymentComplementsIndexRouteImport.update({
    id: '/invoicing/payment-complements/',
    path: '/invoicing/payment-complements/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicingCreditNotesIndexRoute =
  AuthenticatedInvoicingCreditNotesIndexRouteImport.update({
    id: '/invoicing/credit-notes/',
    path: '/invoicing/credit-notes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicingBillOfLadingIndexRoute =
  AuthenticatedInvoicingBillOfLadingIndexRouteImport.update({
    id: '/invoicing/bill-of-lading/',
    path: '/invoicing/bill-of-lading/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkCentersWorkCenterIdEditRoute =
  AuthenticatedWorkCentersWorkCenterIdEditRouteImport.update({
    id: '/work-centers/$workCenterId/edit',
    path: '/work-centers/$workCenterId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeriesEditSeriesIdRoute =
  AuthenticatedSeriesEditSeriesIdRouteImport.update({
    id: '/edit/$seriesId',
    path: '/edit/$seriesId',
    getParentRoute: () => AuthenticatedSeriesRouteRoute,
  } as any)
const AuthenticatedSeriesSeriesIdEditRoute =
  AuthenticatedSeriesSeriesIdEditRouteImport.update({
    id: '/$seriesId/edit',
    path: '/$seriesId/edit',
    getParentRoute: () => AuthenticatedSeriesRouteRoute,
  } as any)
const AuthenticatedProductsProductIdEditRoute =
  AuthenticatedProductsProductIdEditRouteImport.update({
    id: '/products/$productId/edit',
    path: '/products/$productId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMassiveDownloadsViewerDownloadIdRoute =
  AuthenticatedMassiveDownloadsViewerDownloadIdRouteImport.update({
    id: '/massive-downloads/viewer/$downloadId',
    path: '/massive-downloads/viewer/$downloadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdEditRoute =
  AuthenticatedClientsClientIdEditRouteImport.update({
    id: '/clients/$clientId/edit',
    path: '/clients/$clientId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/bienvenido': typeof BienvenidoRoute
  '/configurar-cuenta': typeof ConfigurarCuentaRoute
  '/prueba-gratis': typeof PruebaGratisRoute
  '/series': typeof AuthenticatedSeriesRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/clients/add': typeof AuthenticatedClientsAddRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/invoicing/$invoiceId': typeof AuthenticatedInvoicingInvoiceIdRoute
  '/invoicing/new': typeof AuthenticatedInvoicingNewRoute
  '/massive-downloads/add': typeof AuthenticatedMassiveDownloadsAddRoute
  '/products/add': typeof AuthenticatedProductsAddRoute
  '/series/create': typeof AuthenticatedSeriesCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/$adminId': typeof AuthenticatedUsersAdminIdRoute
  '/users/add': typeof AuthenticatedUsersAddRoute
  '/work-centers/add': typeof AuthenticatedWorkCentersAddRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/catalogs': typeof AuthenticatedCatalogsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/invoicing': typeof AuthenticatedInvoicingIndexRoute
  '/massive-downloads': typeof AuthenticatedMassiveDownloadsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/series/': typeof AuthenticatedSeriesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/timbres': typeof AuthenticatedTimbresIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/viewer': typeof AuthenticatedViewerIndexRoute
  '/work-centers': typeof AuthenticatedWorkCentersIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/massive-downloads/viewer/$downloadId': typeof AuthenticatedMassiveDownloadsViewerDownloadIdRoute
  '/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
  '/series/$seriesId/edit': typeof AuthenticatedSeriesSeriesIdEditRoute
  '/series/edit/$seriesId': typeof AuthenticatedSeriesEditSeriesIdRoute
  '/work-centers/$workCenterId/edit': typeof AuthenticatedWorkCentersWorkCenterIdEditRoute
  '/invoicing/bill-of-lading': typeof AuthenticatedInvoicingBillOfLadingIndexRoute
  '/invoicing/credit-notes': typeof AuthenticatedInvoicingCreditNotesIndexRoute
  '/invoicing/payment-complements': typeof AuthenticatedInvoicingPaymentComplementsIndexRoute
  '/reports/sales': typeof AuthenticatedReportsSalesIndexRoute
}
export interface FileRoutesByTo {
  '/bienvenido': typeof BienvenidoRoute
  '/configurar-cuenta': typeof ConfigurarCuentaRoute
  '/prueba-gratis': typeof PruebaGratisRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/clients/add': typeof AuthenticatedClientsAddRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/invoicing/$invoiceId': typeof AuthenticatedInvoicingInvoiceIdRoute
  '/invoicing/new': typeof AuthenticatedInvoicingNewRoute
  '/massive-downloads/add': typeof AuthenticatedMassiveDownloadsAddRoute
  '/products/add': typeof AuthenticatedProductsAddRoute
  '/series/create': typeof AuthenticatedSeriesCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/$adminId': typeof AuthenticatedUsersAdminIdRoute
  '/users/add': typeof AuthenticatedUsersAddRoute
  '/work-centers/add': typeof AuthenticatedWorkCentersAddRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/catalogs': typeof AuthenticatedCatalogsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/invoicing': typeof AuthenticatedInvoicingIndexRoute
  '/massive-downloads': typeof AuthenticatedMassiveDownloadsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/series': typeof AuthenticatedSeriesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/timbres': typeof AuthenticatedTimbresIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/viewer': typeof AuthenticatedViewerIndexRoute
  '/work-centers': typeof AuthenticatedWorkCentersIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/massive-downloads/viewer/$downloadId': typeof AuthenticatedMassiveDownloadsViewerDownloadIdRoute
  '/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
  '/series/$seriesId/edit': typeof AuthenticatedSeriesSeriesIdEditRoute
  '/series/edit/$seriesId': typeof AuthenticatedSeriesEditSeriesIdRoute
  '/work-centers/$workCenterId/edit': typeof AuthenticatedWorkCentersWorkCenterIdEditRoute
  '/invoicing/bill-of-lading': typeof AuthenticatedInvoicingBillOfLadingIndexRoute
  '/invoicing/credit-notes': typeof AuthenticatedInvoicingCreditNotesIndexRoute
  '/invoicing/payment-complements': typeof AuthenticatedInvoicingPaymentComplementsIndexRoute
  '/reports/sales': typeof AuthenticatedReportsSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/bienvenido': typeof BienvenidoRoute
  '/configurar-cuenta': typeof ConfigurarCuentaRoute
  '/prueba-gratis': typeof PruebaGratisRoute
  '/_authenticated/series': typeof AuthenticatedSeriesRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/add': typeof AuthenticatedClientsAddRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/invoicing/$invoiceId': typeof AuthenticatedInvoicingInvoiceIdRoute
  '/_authenticated/invoicing/new': typeof AuthenticatedInvoicingNewRoute
  '/_authenticated/massive-downloads/add': typeof AuthenticatedMassiveDownloadsAddRoute
  '/_authenticated/products/add': typeof AuthenticatedProductsAddRoute
  '/_authenticated/series/create': typeof AuthenticatedSeriesCreateRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/business': typeof AuthenticatedSettingsBusinessRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/users/$adminId': typeof AuthenticatedUsersAdminIdRoute
  '/_authenticated/users/add': typeof AuthenticatedUsersAddRoute
  '/_authenticated/work-centers/add': typeof AuthenticatedWorkCentersAddRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/catalogs/': typeof AuthenticatedCatalogsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/invoicing/': typeof AuthenticatedInvoicingIndexRoute
  '/_authenticated/massive-downloads/': typeof AuthenticatedMassiveDownloadsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/_authenticated/series/': typeof AuthenticatedSeriesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/timbres/': typeof AuthenticatedTimbresIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/viewer/': typeof AuthenticatedViewerIndexRoute
  '/_authenticated/work-centers/': typeof AuthenticatedWorkCentersIndexRoute
  '/_authenticated/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/_authenticated/massive-downloads/viewer/$downloadId': typeof AuthenticatedMassiveDownloadsViewerDownloadIdRoute
  '/_authenticated/products/$productId/edit': typeof AuthenticatedProductsProductIdEditRoute
  '/_authenticated/series/$seriesId/edit': typeof AuthenticatedSeriesSeriesIdEditRoute
  '/_authenticated/series/edit/$seriesId': typeof AuthenticatedSeriesEditSeriesIdRoute
  '/_authenticated/work-centers/$workCenterId/edit': typeof AuthenticatedWorkCentersWorkCenterIdEditRoute
  '/_authenticated/invoicing/bill-of-lading/': typeof AuthenticatedInvoicingBillOfLadingIndexRoute
  '/_authenticated/invoicing/credit-notes/': typeof AuthenticatedInvoicingCreditNotesIndexRoute
  '/_authenticated/invoicing/payment-complements/': typeof AuthenticatedInvoicingPaymentComplementsIndexRoute
  '/_authenticated/reports/sales/': typeof AuthenticatedReportsSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/bienvenido'
    | '/configurar-cuenta'
    | '/prueba-gratis'
    | '/series'
    | '/settings'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/clients/add'
    | '/errors/$error'
    | '/invoicing/$invoiceId'
    | '/invoicing/new'
    | '/massive-downloads/add'
    | '/products/add'
    | '/series/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/business'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/$adminId'
    | '/users/add'
    | '/work-centers/add'
    | '/apps'
    | '/catalogs'
    | '/chats'
    | '/clients'
    | '/help-center'
    | '/invoicing'
    | '/massive-downloads'
    | '/products'
    | '/quotes'
    | '/series/'
    | '/settings/'
    | '/tasks'
    | '/timbres'
    | '/users'
    | '/viewer'
    | '/work-centers'
    | '/clients/$clientId/edit'
    | '/massive-downloads/viewer/$downloadId'
    | '/products/$productId/edit'
    | '/series/$seriesId/edit'
    | '/series/edit/$seriesId'
    | '/work-centers/$workCenterId/edit'
    | '/invoicing/bill-of-lading'
    | '/invoicing/credit-notes'
    | '/invoicing/payment-complements'
    | '/reports/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bienvenido'
    | '/configurar-cuenta'
    | '/prueba-gratis'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/clients/add'
    | '/errors/$error'
    | '/invoicing/$invoiceId'
    | '/invoicing/new'
    | '/massive-downloads/add'
    | '/products/add'
    | '/series/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/business'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/$adminId'
    | '/users/add'
    | '/work-centers/add'
    | '/apps'
    | '/catalogs'
    | '/chats'
    | '/clients'
    | '/help-center'
    | '/invoicing'
    | '/massive-downloads'
    | '/products'
    | '/quotes'
    | '/series'
    | '/settings'
    | '/tasks'
    | '/timbres'
    | '/users'
    | '/viewer'
    | '/work-centers'
    | '/clients/$clientId/edit'
    | '/massive-downloads/viewer/$downloadId'
    | '/products/$productId/edit'
    | '/series/$seriesId/edit'
    | '/series/edit/$seriesId'
    | '/work-centers/$workCenterId/edit'
    | '/invoicing/bill-of-lading'
    | '/invoicing/credit-notes'
    | '/invoicing/payment-complements'
    | '/reports/sales'
  id:
    | '__root__'
    | '/_authenticated'
    | '/bienvenido'
    | '/configurar-cuenta'
    | '/prueba-gratis'
    | '/_authenticated/series'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/clients/add'
    | '/_authenticated/errors/$error'
    | '/_authenticated/invoicing/$invoiceId'
    | '/_authenticated/invoicing/new'
    | '/_authenticated/massive-downloads/add'
    | '/_authenticated/products/add'
    | '/_authenticated/series/create'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/business'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/users/$adminId'
    | '/_authenticated/users/add'
    | '/_authenticated/work-centers/add'
    | '/_authenticated/apps/'
    | '/_authenticated/catalogs/'
    | '/_authenticated/chats/'
    | '/_authenticated/clients/'
    | '/_authenticated/help-center/'
    | '/_authenticated/invoicing/'
    | '/_authenticated/massive-downloads/'
    | '/_authenticated/products/'
    | '/_authenticated/quotes/'
    | '/_authenticated/series/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/timbres/'
    | '/_authenticated/users/'
    | '/_authenticated/viewer/'
    | '/_authenticated/work-centers/'
    | '/_authenticated/clients/$clientId/edit'
    | '/_authenticated/massive-downloads/viewer/$downloadId'
    | '/_authenticated/products/$productId/edit'
    | '/_authenticated/series/$seriesId/edit'
    | '/_authenticated/series/edit/$seriesId'
    | '/_authenticated/work-centers/$workCenterId/edit'
    | '/_authenticated/invoicing/bill-of-lading/'
    | '/_authenticated/invoicing/credit-notes/'
    | '/_authenticated/invoicing/payment-complements/'
    | '/_authenticated/reports/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BienvenidoRoute: typeof BienvenidoRoute
  ConfigurarCuentaRoute: typeof ConfigurarCuentaRoute
  PruebaGratisRoute: typeof PruebaGratisRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prueba-gratis': {
      id: '/prueba-gratis'
      path: '/prueba-gratis'
      fullPath: '/prueba-gratis'
      preLoaderRoute: typeof PruebaGratisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurar-cuenta': {
      id: '/configurar-cuenta'
      path: '/configurar-cuenta'
      fullPath: '/configurar-cuenta'
      preLoaderRoute: typeof ConfigurarCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenido': {
      id: '/bienvenido'
      path: '/bienvenido'
      fullPath: '/bienvenido'
      preLoaderRoute: typeof BienvenidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series': {
      id: '/_authenticated/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedSeriesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-centers/': {
      id: '/_authenticated/work-centers/'
      path: '/work-centers'
      fullPath: '/work-centers'
      preLoaderRoute: typeof AuthenticatedWorkCentersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viewer/': {
      id: '/_authenticated/viewer/'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof AuthenticatedViewerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timbres/': {
      id: '/_authenticated/timbres/'
      path: '/timbres'
      fullPath: '/timbres'
      preLoaderRoute: typeof AuthenticatedTimbresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/series/': {
      id: '/_authenticated/series/'
      path: '/'
      fullPath: '/series/'
      preLoaderRoute: typeof AuthenticatedSeriesIndexRouteImport
      parentRoute: typeof AuthenticatedSeriesRouteRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/massive-downloads/': {
      id: '/_authenticated/massive-downloads/'
      path: '/massive-downloads'
      fullPath: '/massive-downloads'
      preLoaderRoute: typeof AuthenticatedMassiveDownloadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoicing/': {
      id: '/_authenticated/invoicing/'
      path: '/invoicing'
      fullPath: '/invoicing'
      preLoaderRoute: typeof AuthenticatedInvoicingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogs/': {
      id: '/_authenticated/catalogs/'
      path: '/catalogs'
      fullPath: '/catalogs'
      preLoaderRoute: typeof AuthenticatedCatalogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-centers/add': {
      id: '/_authenticated/work-centers/add'
      path: '/work-centers/add'
      fullPath: '/work-centers/add'
      preLoaderRoute: typeof AuthenticatedWorkCentersAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/add': {
      id: '/_authenticated/users/add'
      path: '/users/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof AuthenticatedUsersAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$adminId': {
      id: '/_authenticated/users/$adminId'
      path: '/users/$adminId'
      fullPath: '/users/$adminId'
      preLoaderRoute: typeof AuthenticatedUsersAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/business': {
      id: '/_authenticated/settings/business'
      path: '/business'
      fullPath: '/settings/business'
      preLoaderRoute: typeof AuthenticatedSettingsBusinessRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/series/create': {
      id: '/_authenticated/series/create'
      path: '/create'
      fullPath: '/series/create'
      preLoaderRoute: typeof AuthenticatedSeriesCreateRouteImport
      parentRoute: typeof AuthenticatedSeriesRouteRoute
    }
    '/_authenticated/products/add': {
      id: '/_authenticated/products/add'
      path: '/products/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof AuthenticatedProductsAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/massive-downloads/add': {
      id: '/_authenticated/massive-downloads/add'
      path: '/massive-downloads/add'
      fullPath: '/massive-downloads/add'
      preLoaderRoute: typeof AuthenticatedMassiveDownloadsAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoicing/new': {
      id: '/_authenticated/invoicing/new'
      path: '/invoicing/new'
      fullPath: '/invoicing/new'
      preLoaderRoute: typeof AuthenticatedInvoicingNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoicing/$invoiceId': {
      id: '/_authenticated/invoicing/$invoiceId'
      path: '/invoicing/$invoiceId'
      fullPath: '/invoicing/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicingInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/add': {
      id: '/_authenticated/clients/add'
      path: '/clients/add'
      fullPath: '/clients/add'
      preLoaderRoute: typeof AuthenticatedClientsAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/sales/': {
      id: '/_authenticated/reports/sales/'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoicing/payment-complements/': {
      id: '/_authenticated/invoicing/payment-complements/'
      path: '/invoicing/payment-complements'
      fullPath: '/invoicing/payment-complements'
      preLoaderRoute: typeof AuthenticatedInvoicingPaymentComplementsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoicing/credit-notes/': {
      id: '/_authenticated/invoicing/credit-notes/'
      path: '/invoicing/credit-notes'
      fullPath: '/invoicing/credit-notes'
      preLoaderRoute: typeof AuthenticatedInvoicingCreditNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoicing/bill-of-lading/': {
      id: '/_authenticated/invoicing/bill-of-lading/'
      path: '/invoicing/bill-of-lading'
      fullPath: '/invoicing/bill-of-lading'
      preLoaderRoute: typeof AuthenticatedInvoicingBillOfLadingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-centers/$workCenterId/edit': {
      id: '/_authenticated/work-centers/$workCenterId/edit'
      path: '/work-centers/$workCenterId/edit'
      fullPath: '/work-centers/$workCenterId/edit'
      preLoaderRoute: typeof AuthenticatedWorkCentersWorkCenterIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series/edit/$seriesId': {
      id: '/_authenticated/series/edit/$seriesId'
      path: '/edit/$seriesId'
      fullPath: '/series/edit/$seriesId'
      preLoaderRoute: typeof AuthenticatedSeriesEditSeriesIdRouteImport
      parentRoute: typeof AuthenticatedSeriesRouteRoute
    }
    '/_authenticated/series/$seriesId/edit': {
      id: '/_authenticated/series/$seriesId/edit'
      path: '/$seriesId/edit'
      fullPath: '/series/$seriesId/edit'
      preLoaderRoute: typeof AuthenticatedSeriesSeriesIdEditRouteImport
      parentRoute: typeof AuthenticatedSeriesRouteRoute
    }
    '/_authenticated/products/$productId/edit': {
      id: '/_authenticated/products/$productId/edit'
      path: '/products/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/massive-downloads/viewer/$downloadId': {
      id: '/_authenticated/massive-downloads/viewer/$downloadId'
      path: '/massive-downloads/viewer/$downloadId'
      fullPath: '/massive-downloads/viewer/$downloadId'
      preLoaderRoute: typeof AuthenticatedMassiveDownloadsViewerDownloadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId/edit': {
      id: '/_authenticated/clients/$clientId/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthenticatedClientsClientIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSeriesRouteRouteChildren {
  AuthenticatedSeriesCreateRoute: typeof AuthenticatedSeriesCreateRoute
  AuthenticatedSeriesIndexRoute: typeof AuthenticatedSeriesIndexRoute
  AuthenticatedSeriesSeriesIdEditRoute: typeof AuthenticatedSeriesSeriesIdEditRoute
  AuthenticatedSeriesEditSeriesIdRoute: typeof AuthenticatedSeriesEditSeriesIdRoute
}

const AuthenticatedSeriesRouteRouteChildren: AuthenticatedSeriesRouteRouteChildren =
  {
    AuthenticatedSeriesCreateRoute: AuthenticatedSeriesCreateRoute,
    AuthenticatedSeriesIndexRoute: AuthenticatedSeriesIndexRoute,
    AuthenticatedSeriesSeriesIdEditRoute: AuthenticatedSeriesSeriesIdEditRoute,
    AuthenticatedSeriesEditSeriesIdRoute: AuthenticatedSeriesEditSeriesIdRoute,
  }

const AuthenticatedSeriesRouteRouteWithChildren =
  AuthenticatedSeriesRouteRoute._addFileChildren(
    AuthenticatedSeriesRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsBusinessRoute: typeof AuthenticatedSettingsBusinessRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsBusinessRoute: AuthenticatedSettingsBusinessRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSeriesRouteRoute: typeof AuthenticatedSeriesRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsAddRoute: typeof AuthenticatedClientsAddRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedInvoicingInvoiceIdRoute: typeof AuthenticatedInvoicingInvoiceIdRoute
  AuthenticatedInvoicingNewRoute: typeof AuthenticatedInvoicingNewRoute
  AuthenticatedMassiveDownloadsAddRoute: typeof AuthenticatedMassiveDownloadsAddRoute
  AuthenticatedProductsAddRoute: typeof AuthenticatedProductsAddRoute
  AuthenticatedUsersAdminIdRoute: typeof AuthenticatedUsersAdminIdRoute
  AuthenticatedUsersAddRoute: typeof AuthenticatedUsersAddRoute
  AuthenticatedWorkCentersAddRoute: typeof AuthenticatedWorkCentersAddRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedCatalogsIndexRoute: typeof AuthenticatedCatalogsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedInvoicingIndexRoute: typeof AuthenticatedInvoicingIndexRoute
  AuthenticatedMassiveDownloadsIndexRoute: typeof AuthenticatedMassiveDownloadsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTimbresIndexRoute: typeof AuthenticatedTimbresIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedViewerIndexRoute: typeof AuthenticatedViewerIndexRoute
  AuthenticatedWorkCentersIndexRoute: typeof AuthenticatedWorkCentersIndexRoute
  AuthenticatedClientsClientIdEditRoute: typeof AuthenticatedClientsClientIdEditRoute
  AuthenticatedMassiveDownloadsViewerDownloadIdRoute: typeof AuthenticatedMassiveDownloadsViewerDownloadIdRoute
  AuthenticatedProductsProductIdEditRoute: typeof AuthenticatedProductsProductIdEditRoute
  AuthenticatedWorkCentersWorkCenterIdEditRoute: typeof AuthenticatedWorkCentersWorkCenterIdEditRoute
  AuthenticatedInvoicingBillOfLadingIndexRoute: typeof AuthenticatedInvoicingBillOfLadingIndexRoute
  AuthenticatedInvoicingCreditNotesIndexRoute: typeof AuthenticatedInvoicingCreditNotesIndexRoute
  AuthenticatedInvoicingPaymentComplementsIndexRoute: typeof AuthenticatedInvoicingPaymentComplementsIndexRoute
  AuthenticatedReportsSalesIndexRoute: typeof AuthenticatedReportsSalesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSeriesRouteRoute: AuthenticatedSeriesRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsAddRoute: AuthenticatedClientsAddRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedInvoicingInvoiceIdRoute: AuthenticatedInvoicingInvoiceIdRoute,
  AuthenticatedInvoicingNewRoute: AuthenticatedInvoicingNewRoute,
  AuthenticatedMassiveDownloadsAddRoute: AuthenticatedMassiveDownloadsAddRoute,
  AuthenticatedProductsAddRoute: AuthenticatedProductsAddRoute,
  AuthenticatedUsersAdminIdRoute: AuthenticatedUsersAdminIdRoute,
  AuthenticatedUsersAddRoute: AuthenticatedUsersAddRoute,
  AuthenticatedWorkCentersAddRoute: AuthenticatedWorkCentersAddRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedCatalogsIndexRoute: AuthenticatedCatalogsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedInvoicingIndexRoute: AuthenticatedInvoicingIndexRoute,
  AuthenticatedMassiveDownloadsIndexRoute:
    AuthenticatedMassiveDownloadsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTimbresIndexRoute: AuthenticatedTimbresIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedViewerIndexRoute: AuthenticatedViewerIndexRoute,
  AuthenticatedWorkCentersIndexRoute: AuthenticatedWorkCentersIndexRoute,
  AuthenticatedClientsClientIdEditRoute: AuthenticatedClientsClientIdEditRoute,
  AuthenticatedMassiveDownloadsViewerDownloadIdRoute:
    AuthenticatedMassiveDownloadsViewerDownloadIdRoute,
  AuthenticatedProductsProductIdEditRoute:
    AuthenticatedProductsProductIdEditRoute,
  AuthenticatedWorkCentersWorkCenterIdEditRoute:
    AuthenticatedWorkCentersWorkCenterIdEditRoute,
  AuthenticatedInvoicingBillOfLadingIndexRoute:
    AuthenticatedInvoicingBillOfLadingIndexRoute,
  AuthenticatedInvoicingCreditNotesIndexRoute:
    AuthenticatedInvoicingCreditNotesIndexRoute,
  AuthenticatedInvoicingPaymentComplementsIndexRoute:
    AuthenticatedInvoicingPaymentComplementsIndexRoute,
  AuthenticatedReportsSalesIndexRoute: AuthenticatedReportsSalesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BienvenidoRoute: BienvenidoRoute,
  ConfigurarCuentaRoute: ConfigurarCuentaRoute,
  PruebaGratisRoute: PruebaGratisRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
